#!/usr/bin/env bash
# Render the walkingpad LaunchAgent plist. The Argo bearer is NOT baked in — the
# rendered plist resolves it AT SPAWN from the secrets cache via `secrets-run
# read`.
#
# This script used to write the token straight into <EnvironmentVariables> in
# cleartext, so re-running it silently regressed a completed hardening: a
# plaintext bearer token on disk, on the machine whose entire secrets design is
# "no plaintext secret on the mini". launchd has no `EnvironmentFile=`
# equivalent, so the injection has to happen in a wrapper shell — same shape as
# the collie LaunchAgent, with `secrets-run read` in place of a plaintext .env
# so nothing lands on disk at all.
#
# Two consequences worth naming:
#   - The installer no longer needs the token in its own environment. Nothing is
#     resolved at INSTALL time; the value is resolved at RUN time, every spawn.
#   - The output is therefore deterministic, so re-running is a true no-op
#     instead of re-baking whatever the token happened to be that day.
#
# Usage:  scripts/install-launch-agent.sh [<template>] <output-path>
#
# The template argument is accepted and IGNORED. The plist content is owned by
# this script because the no-plaintext-token shape is a security invariant, not
# a layout preference — a separate template file is exactly how it regressed.
# The two-argument form survives only so `make up` keeps working unchanged.

set -euo pipefail

usage() {
  echo "usage: $0 [<template>] <output>" >&2
  exit 64
}

case $# in
  1) OUTPUT=$1 ;;
  2)
    OUTPUT=$2
    echo "note: template argument ignored ($1) — plist content is generated by this script"
    ;;
  *) usage ;;
esac

ARGO_REF="op://common/api/SECRET"
ARGO_URL="https://argo.jkrumm.com/api"
APP_BIN="/Applications/WalkingPad.app/Contents/MacOS/walkingpad"

# Absolute path, because launchd starts an agent with no shell profile and
# ~/.local/bin is not on its default PATH. The rendered plist pins PATH too —
# belt and braces, because a PATH miss degrades silently to "sync disabled"
# rather than erroring.
SECRETS_RUN="$(command -v secrets-run || true)"
SECRETS_RUN="${SECRETS_RUN:-$HOME/.local/bin/secrets-run}"

# Preflight only — the value is discarded, never stored and never rendered. A
# failure here is informational: Argo sync is strictly optional (PRD §1), so the
# daemon runs fine without it and the install must not fail over it.
# `</dev/null` so a backend that wants stdin can't wedge the installer.
if [[ -x "$SECRETS_RUN" ]]; then
  if "$SECRETS_RUN" read "$ARGO_REF" </dev/null >/dev/null 2>&1; then
    echo "argo sync: $ARGO_REF resolves — the agent picks it up at spawn"
  else
    echo "argo sync: $ARGO_REF does not resolve — installing anyway; the daemon runs without sync"
  fi
else
  echo "argo sync: no secrets-run at $SECRETS_RUN — installing anyway; the daemon runs without sync"
fi

# Write to a temp file first so a failed render can't truncate $OUTPUT.
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.jkrumm.walkingpad</string>

  <!-- The Argo bearer is resolved AT SPAWN from the secrets cache, never baked
       into this file. It used to sit here in cleartext under
       EnvironmentVariables — on the machine whose entire secrets design is "no
       plaintext secret on disk". launchd has no \`EnvironmentFile=\`, so the
       injection has to happen in a wrapper shell; this is the same shape the
       collie LaunchAgent uses, with \`secrets-run read\` in place of a plaintext
       .env so nothing lands on disk at all.

       Degrades rather than fails: an unresolvable token disables argo sync and
       the treadmill daemon runs on (PRD §1 — sync is strictly optional). That
       matches what the installer did at render time, so a stale cache does not
       become a walkingpad outage. The warning goes to stderr, which is a
       durable log rather than an unlinked /tmp inode. -->
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>-c</string>
    <string>T=\$(${SECRETS_RUN} read ${ARGO_REF} 2&gt;/dev/null) &amp;&amp; [ -n "\$T" ] &amp;&amp; export KSWP_ARGO_TOKEN="\$T" || echo "walkingpad: KSWP_ARGO_TOKEN unresolvable via secrets-run (${ARGO_REF}) — argo sync disabled" &gt;&amp;2; exec ${APP_BIN} serve</string>
  </array>

  <key>RunAtLoad</key>          <true/>
  <key>KeepAlive</key>          <true/>
  <key>ProcessType</key>        <string>Interactive</string>

  <!-- ~/Library/Logs, not /tmp. macOS's periodic cleanup sweeps /tmp files
       untouched for 3+ days and a KeepAlive agent opens its stdio ONCE at
       spawn, so after a sweep it writes into an UNLINKED inode forever.
       Measured on the mini 2026-07-31: \`lsof\` held /private/tmp/walkingpad.log
       open while \`ls\` found no such file. walkingpad.err survived only because
       it is written ~1 line/sec and the sweep skips recently-modified files —
       it was 35 MB with no rotation. Rotation is com.jkrumm.log-rotate's job
       (copytruncate, since launchd cannot be told to reopen an fd). -->
  <key>StandardOutPath</key>    <string>${HOME}/Library/Logs/walkingpad.log</string>
  <key>StandardErrorPath</key>  <string>${HOME}/Library/Logs/walkingpad.err</string>

  <!-- PATH is load-bearing: launchd starts an agent with no shell profile at
       all, and \`secrets-run\` lives in ~/.local/bin, which is not on launchd's
       default PATH. It is also invoked by absolute path above — belt and
       braces, because a PATH miss here degrades silently to "sync disabled"
       rather than erroring. HOME matters for the same reason: secrets-run
       resolves both the backend marker and the encrypted cache relative to it. -->
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>             <string>${HOME}/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    <key>HOME</key>             <string>${HOME}</string>
    <key>KSWP_ARGO_URL</key>    <string>${ARGO_URL}</string>
  </dict>
</dict>
</plist>
EOF

# Fail before touching $OUTPUT if the render is not a valid plist.
plutil -lint "$TMP" >/dev/null

# 0600 not because it holds a secret any more — it holds none — but because
# nothing other than launchd (running as this user) has any business reading it.
install -m 0600 "$TMP" "$OUTPUT"
echo "wrote $OUTPUT"
